setting:
  fs: 16000
  speed: 343.8
  xyz_min: 0
  xyz_max: 10
  model_type: AVR
  dir_ch: 8
  batch_size: 8
  load_workers: 4
param:
  near: 0
  far: 6
  n_samples: 64
  n_azi: 64
  n_ele: 32
  pathloss: 1.5
model:
  signal_output_dim: 1600
  pos_encoding_sigma:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  dir_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  tx_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  sigma_encoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 128
  sigma_decoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 128
  signal_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 512
  channel_embed:
    is_sigma_encoder: true
    is_sigma_decoder: true
    is_signal_network: true
