study:
  study_name: avr_optuna
  n_trials: 100
  direction: minimize
doa_metric:
  algorithm: NormMUSIC
  n_fft: 512
  fallback_value: 999.0
setting:
  fs: 16000
  speed: 343.8
  xyz_min: 0
  xyz_max: 10
  model_type: AVR++
  ch_num: 8
  T_max: 8300
  grad_clip_norm: 1
  resume: True
  batch_size: 8
  save_best_k: 10
  val_freq: 166
  load_workers: 4
model:
  signal_output_dim: 1600
  pos_encoding_sigma:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  dir_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  tx_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  sigma_encoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
  sigma_decoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
  signal_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
fixed:
  param.near: 0
  param.far: 6
  param.amplitude_loss_weight: 4
  param.softargmax_beta: 100
  param.n_ele: 32
  param.pathloss: 1.5
  model.sigma_encoder_network.n_hidden_layers: 3
  model.sigma_decoder_network.n_hidden_layers: 3
  model.signal_network.n_hidden_layers: 3
search_space:
  param.lr:
    type: float
    low: 1.0e-6
    high: 1.0e-4
    log: True
  param.eta_min:
    type: float
    low: 1.0e-7
    high: 1.0e-5
    log: True
  param.n_samples:
    type: int
    low: 40
    high: 80
  param.n_azi:
    type: int
    low: 48
    high: 80
  param.weight_decay:
    type: float
    low: 0.0
    high: 1.0e-3
  param.spec_loss_weight:
    type: float
    low: 0
    high: 100
  param.angle_loss_weight:
    type: float
    low: 0
    high: 100
  param.time_loss_weight:
    type: float
    low: 0
    high: 100
  param.energy_loss_weight:
    type: float
    low: 0
    high: 100
  param.multistft_loss_weight:
    type: float
    low: 0
    high: 100
  param.das_loss_weight:
    type: float
    low: 0
    high: 100
  model.sigma_encoder_network.n_neurons:
    type: categorical
    choices:
      - 32
      - 64
      - 128
      - 256
      - 512
  model.sigma_decoder_network.n_neurons:
    type: categorical
    choices:
      - 32
      - 64
      - 128
      - 256
      - 512
  model.signal_network.n_neurons:
    type: categorical
    choices:
      - 128
      - 256
      - 512
  model.channel_embed.is_sigma_encoder:
    type: categorical
    choices:
      - True
      - False
  model.channel_embed.is_sigma_decoder:
    type: categorical
    choices:
      - True
      - False
  model.channel_embed.is_signal_network:
    type: categorical
    choices:
      - True
      - False
