model:
  channel_embed:
    is_sigma_decoder: true
    is_sigma_encoder: false
    is_signal_network: true
  dir_encoding_sig:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid
  leaky_relu: 0.03
  pos_encoding_sigma:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid
  sigma_decoder_network:
    activation: ReLU
    n_hidden_layers: 3
    n_neurons: 64
    otype: CutlassMLP
    output_activation: None
  sigma_encoder_network:
    activation: ReLU
    n_hidden_layers: 3
    n_neurons: 512
    otype: CutlassMLP
    output_activation: None
  signal_network:
    activation: ReLU
    n_hidden_layers: 3
    n_neurons: 128
    otype: CutlassMLP
    output_activation: None
  signal_output_dim: 1600
  tx_encoding_sig:
    base_resolution: 16
    log2_hashmap_size: 18
    n_features_per_level: 2
    n_levels: 20
    otype: HashGrid
render:
  far: 6
  fs: 16000
  n_azi: 53
  n_ele: 32
  n_samples: 53
  near: 0
  pathloss: 1.5
  speed: 343.8
  xyz_max: 10
  xyz_min: 0
train:
  T_max: 49800
  amplitude_loss_weight: 4
  angle_loss_weight: 59.144183380769505
  batch_size: 8
  beta: 100
  das_ce_loss_weight: 0
  das_reg_loss_weight: 59.57808663675326
  energy_loss_weight: 61.76998963190817
  eta_min: 2.4266935675591545e-06
  load_ckpt: true
  lr: 1.909259263025426e-05
  multistft_loss_weight: 8.132613148605039
  save_freq: 166
  spec_loss_weight: 28.529931487360106
  time_loss_weight: 70.56056442265249
  total_iterations: 49800
  val_freq: 166
  weight_decay: 0.0008331071674373583
