doa_metric:
  algorithm: NormMUSIC
  n_fft: 512
  fallback_value: 999.0

setting:
  fs: 16000
  speed: 343.8
  xyz_min: 0
  xyz_max: 10
  model_type: AVR++
  ch_num: 8
  T_max: 8300
  grad_clip_norm: 1
  resume: True
  batch_size: 8
  save_best_k: 10
  val_freq: 166
  load_workers: 4

param:
  near: 0
  far: 6
  n_samples: 75
  n_azi: 68
  n_ele: 32
  pathloss: 1.5
  lr: 2.932298131746054e-05
  eta_min: 1.2074360110207406e-05
  weight_decay: 0.0006624198017688447
  spec_loss_weight: 96.74715266316646
  amplitude_loss_weight: 4
  angle_loss_weight: 6.751605765374784
  time_loss_weight: 89.76190213257655
  energy_loss_weight: 17.580998331715325
  multistft_loss_weight: 48.983894799952324
  das_loss_weight: 98.87006827660845
  softargmax_beta: 100

model:
  signal_output_dim: 1600
  pos_encoding_sigma:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  dir_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  tx_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  sigma_encoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 256
  sigma_decoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 64
  signal_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 1024
  channel_embed:
    is_sigma_encoder: false
    is_sigma_decoder: false
    is_signal_network: true