doa_metric:
  algorithm: NormMUSIC
  n_fft: 512
  fallback_value: 999.0

setting:
  fs: 16000
  speed: 343.8
  xyz_min: 0
  xyz_max: 10
  model_type: AVR+
  ch_num: 8
  T_max: 66400
  grad_clip_norm: 1
  resume: True
  batch_size: 8
  save_best_k: 10
  val_freq: 1328
  load_workers: 4

param:
  near: 0
  far: 6
  n_samples: 66
  n_azi: 65
  n_ele: 32
  pathloss: 1.5
  lr: 5.950279183645823e-06
  eta_min: 3.521912904028211e-07
  weight_decay: 0.0006366605485390508
  spec_loss_weight: 9.33277077312557
  amplitude_loss_weight: 4
  angle_loss_weight: 94.87175603668567
  time_loss_weight: 45.6159821099346
  energy_loss_weight: 61.25584459181117
  multistft_loss_weight: 9.07399178594612

model:
  signal_output_dim: 1600
  pos_encoding_sigma:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  dir_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  tx_encoding_sig:
    otype: HashGrid
    n_levels: 20
    n_features_per_level: 2
    log2_hashmap_size: 18
    base_resolution: 16
  sigma_encoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 32
  sigma_decoder_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 32
  signal_network:
    otype: CutlassMLP
    activation: ReLU
    output_activation: None
    n_hidden_layers: 3
    n_neurons: 1024
  channel_embed:
    is_sigma_encoder: false
    is_sigma_decoder: false
    is_signal_network: false