setting:
  gpus: 1
  model_type: NAF
  epochs: 50
  resume: True
  batch_size: 20
  save_best_k: 10

param:
  mag_alpha: 1.0
  phase_alpha: 7.397822012469649
  lr_init: 4.751320720179008e-05
  lr_decay: 0.24902999941702444
  weight_decay_grid: 1.0e-2
  weight_decay_main: 0.0
  reg_eps: 0.053167569016486366
  pixel_count: 2147
  layers: 4
  layers_residual: 2
  features: 64
  grid_features: 64
  activation_func_name: default
  grid_gap: 0.25
  bandwith_init: 0.25
  position_float: 0.1
  min_bandwidth: 0.1
  max_bandwidth: 0.5
  embed_xyz_num_freqs: 10
  embed_xyz_max_freq: 7
  embed_time_num_freqs: 10
  embed_time_max_freq: 10
  embed_freq_num_freqs: 10
  embed_freq_max_freq: 10
  xy_min:
    - 0
    - 0
  xy_max:
    - 6.110
    - 8.807

doa_metric:
  algorithm: NormMUSIC