study:
  study_name: naf_optuna
  direction: minimize
  n_trials: 100

doa_metric:
  algorithm: NormMUSIC
  fallback_value: 999.0

setting:
  gpus: 1
  model_type: NAF+
  ch_num: 8
  epochs: 50
  resume: True
  batch_size: 20
  save_best_k: 10

fixed:
  gpus: 1
  epochs: 200
  resume: 0
  batch_size: 20
  mag_alpha: 1.0
  weight_decay_grid: 1.0e-2
  weight_decay_main: 0.0
  grid_features: 64
  ch_num: 8
  activation_func_name: default
  grid_gap: 0.25
  bandwith_init: 0.25
  position_float: 0.1
  min_bandwidth: 0.1
  max_bandwidth: 0.5
  embed_xyz_num_freqs: 10
  embed_xyz_max_freq: 7
  embed_time_num_freqs: 10
  embed_time_max_freq: 10
  embed_freq_num_freqs: 10
  embed_freq_max_freq: 10
  xy_min:
    - 0
    - 0
  xy_max:
    - 6.110
    - 8.807
  save_best_k: 10

search_space:
  layers:
    type: int
    low: 4
    high: 12
  layers_residual:
    type: int
    low: 0
    high: 3
  features:
    type: categorical
    choices:
      - 64
      - 128
      - 256
      - 512
      - 1024
  reg_eps:
    type: float
    low: 0.0
    high: 0.2
  pixel_count:
    type: int
    low: 200
    high: 4000
  lr_init:
    type: float
    low: 1.0e-5
    high: 1.0e-2
    log: True
  lr_decay:
    type: float
    low: 5.0e-2
    high: 5.0e-1
    log: True
  phase_alpha:
    type: float
    low: 0.1
    high: 10.0
